In [12]:
from keras.utils import to_categorical
import numpy as np
from glob import glob
import os
import re


In [4]:
a = np.arange(10)

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = to_categorical(a, 10)

In [7]:
b

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [13]:
DATA_DIR = "/home/hangwu/code/ResNet-Tensorflow/tiny-imagenet-200/train/"
train_images = sorted(glob(os.path.join(DATA_DIR, "*", "*", "*.JPEG")))
label_list = [re.findall(r"n\d+", im_path)[0] for im_path in train_images]

In [14]:
label_list

['n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n01443537',
 'n014

In [15]:
num = len(set(label_list))

In [18]:
hashmap = {}
for i, label in enumerate(sorted(set(label_list))):
    hashmap[label] = i
print(hashmap)

{'n03444034': 0, 'n02099712': 1, 'n01855672': 2, 'n03670208': 3, 'n02791270': 4, 'n02823428': 5, 'n01917289': 6, 'n04070727': 7, 'n07747607': 8, 'n07753592': 9, 'n02699494': 10, 'n03160309': 11, 'n07920052': 12, 'n02843684': 13, 'n03930313': 14, 'n03085013': 15, 'n02002724': 16, 'n02074367': 17, 'n02403003': 18, 'n02236044': 19, 'n02279972': 20, 'n04008634': 21, 'n09332890': 22, 'n03796401': 23, 'n02415577': 24, 'n02321529': 25, 'n04265275': 26, 'n04465501': 27, 'n09428293': 28, 'n01984695': 29, 'n04371430': 30, 'n07875152': 31, 'n01983481': 32, 'n02480495': 33, 'n02814860': 34, 'n03970156': 35, 'n03544143': 36, 'n02486410': 37, 'n02917067': 38, 'n02504458': 39, 'n01443537': 40, 'n02423022': 41, 'n03026506': 42, 'n02927161': 43, 'n04540053': 44, 'n02085620': 45, 'n02948072': 46, 'n04532106': 47, 'n02233338': 48, 'n03706229': 49, 'n04376876': 50, 'n02988304': 51, 'n02669723': 52, 'n03126707': 53, 'n04254777': 54, 'n03891332': 55, 'n03424325': 56, 'n04532670': 57, 'n07579787': 58, 'n0774

In [19]:
hashmap = {}
for i, label in enumerate(sorted(set(label_list))):
    hashmap[label] = i
print(hashmap)

{'n01443537': 0, 'n01629819': 1, 'n01641577': 2, 'n01644900': 3, 'n01698640': 4, 'n01742172': 5, 'n01768244': 6, 'n01770393': 7, 'n01774384': 8, 'n01774750': 9, 'n01784675': 10, 'n01855672': 11, 'n01882714': 12, 'n01910747': 13, 'n01917289': 14, 'n01944390': 15, 'n01945685': 16, 'n01950731': 17, 'n01983481': 18, 'n01984695': 19, 'n02002724': 20, 'n02056570': 21, 'n02058221': 22, 'n02074367': 23, 'n02085620': 24, 'n02094433': 25, 'n02099601': 26, 'n02099712': 27, 'n02106662': 28, 'n02113799': 29, 'n02123045': 30, 'n02123394': 31, 'n02124075': 32, 'n02125311': 33, 'n02129165': 34, 'n02132136': 35, 'n02165456': 36, 'n02190166': 37, 'n02206856': 38, 'n02226429': 39, 'n02231487': 40, 'n02233338': 41, 'n02236044': 42, 'n02268443': 43, 'n02279972': 44, 'n02281406': 45, 'n02321529': 46, 'n02364673': 47, 'n02395406': 48, 'n02403003': 49, 'n02410509': 50, 'n02415577': 51, 'n02423022': 52, 'n02437312': 53, 'n02480495': 54, 'n02481823': 55, 'n02486410': 56, 'n02504458': 57, 'n02509815': 58, 'n0266

In [20]:
label_num_list = [hashmap[label] for label in label_list]

In [21]:
label_num_list

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [22]:
to_categorical(label_num_list)

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)